### ISSUE TITLE
Use `ape::as.phylo` methods

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/phylogenetic#1]
The `phylo` class of the `ape` package seems to be a very popular storage method for phylogenetic trees, so it is worthwhile either storing this package's objects as `phylo` objects or create conversion functions to take advantage of the `ape` package.

**Comment by gvegayon** [comment]
Found the formal definition of `phylo` objects (not trivial at all) from [here](http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf)

**Definition of Formats for Coding Phylogenetic Trees in R**, *Emmanuel Paradis*, October 24, 2012

> The class "phylo" is used to code “acyclical” phylogenetic trees. These trees have no reticulations, and all their internal nodes are of degree 3 or more, except the root (in the case of rooted trees) which is of degree 2 or more. An object of class "phylo" is a list with the following mandatory elements:
> 
> 1. A numeric matrix named edge with two columns and as many rows as there are branches in the tree;
> 
> 2. A character vector of length n named tip.label with the labels of the tips;
> 
> 3. An integer value named Nnode giving the number of (internal) nodes;
> 
> 4. An attribute class equal to "phylo".
> 
> In the matrix edge, each branch is coded by the nodes it connects: tips are coded 1, . . . , n, and internal nodes are coded n+ 1, . . . , n+m (n+ 1 is the root). Both series are numbered without gaps.
> 
> The matrix edge has the following properties:
> 
> * The first column has only values greater than n (thus, values less than or equal to n appear only in the second column).
> 
> * All nodes appear in the first column at least twice.
> 
> * The number of occurrences of a node in the first column is related to the nature of the node: twice if it is dichotomous (i.e., of degree 3), three times if it is trichotomous (degree 4), and so on.
> 
> * All elements, except the root n + 1, appear once in the second column.
> 
> This representation is used for rooted and unrooted trees. For the latter, the
> position of the root is arbitrary

**Comment by gvegayon** [comment]
Found a couple of R packages that might be of interest for the project:

1. https://cran.r-project.org/web/packages/OutbreakTools/index.html
2. https://cran.r-project.org/web/packages/outbreaker/index.html
3. https://sites.google.com/site/therepiproject/r-pac/outbreaker

All from the R-epi project.

**Comment by bschilder** [comment]
I see this was closed, but was this implemented?

```R
URL <- "http://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz100way/hg38.100way.commonNames.nh"
tree_path <- file.path("~/Desktop",basename(URL))
download.file(URL,
              destfile = tree_path,
              method = "wget")

#### Remove ";" at the end, which causes errors ####
l <- readLines(tree_path)
l2 <- gsub(";","",l)
writeLines(l2,tree_path)
# tr <- ape::read.tree(file = tree_path)
tr <- aphylo::read_nhx(tree_path)
ape::as.phylo(tr)
```

```
Error in UseMethod("as.phylo") : 
  no applicable method for 'as.phylo' applied to an object of class "list"
```

**Comment by gvegayon** [comment]
The methods `plot`, `Ntip`, `Nnode`, and `Nedge` are implemented. Regarding reading the file, it seems to be a problem with `ape`, not with `aphylo`. I tried your code, and I get nothing from reading either directly from the file or from the text object in R.
